import React from 'react'
import reactDOM from 'react-dom';
import './app.less';
import Tree from './components/Tree.jsx';

let config = {
  type: 'array',
  parentId: 'pid',
  id: 'shiroConf'
}
let treeData = [{"id":0,"shiroConf":"*","name":"god"},{"id":1,"shiroConf":"mainPage","name":"首页"},{"id":2,"shiroConf":"mainPage:view","name":"查看及搜索"},{"id":3,"shiroConf":"dataCenter","name":"数据中心"},{"id":4,"shiroConf":"dataCenter:app","name":"小程序数据"},{"id":5,"shiroConf":"dataCenter:app:view","name":"查看及搜索"},{"id":160,"shiroConf":"resource","name":"资源管理"},{"id":161,"shiroConf":"resource:view","name":"查看及搜索"},{"id":162,"shiroConf":"resource:update","name":"处理资源"},{"id":60,"shiroConf":"template","name":"检测套餐库"},{"id":61,"shiroConf":"template:view","name":"查看及搜索"},{"id":62,"shiroConf":"template:create","name":"新建套餐"},{"id":63,"shiroConf":"template:update","name":"编辑套餐"},{"id":64,"shiroConf":"template:delete","name":"删除套餐"},{"id":130,"shiroConf":"trade","name":"交易管理"},{"id":131,"shiroConf":"trade:view","name":"查看及搜索"},{"id":132,"shiroConf":"trade:confirmPaid","name":"到款确认"},{"id":220,"shiroConf":"stuff","name":"账号权限"},{"id":222,"shiroConf":"stuff:manage:department","name":"添加/编辑/删除部门"},{"id":232,"shiroConf":"stuff:manage","name":"组织及人员管理"},{"id":236,"shiroConf":"stuff:manage:view","name":"查看人员"},{"id":233,"shiroConf":"stuff:manage:add","name":"添加人员"},{"id":234,"shiroConf":"stuff:manage:update","name":"编辑人员"},{"id":235,"shiroConf":"stuff:manage:delete","name":"删除人员"},{"id":238,"shiroConf":"stuff:role","name":"角色及权限管理"},{"id":239,"shiroConf":"stuff:role:view","name":"查看角色"},{"id":240,"shiroConf":"stuff:role:add","name":"添加角色"},{"id":241,"shiroConf":"stuff:role:name","name":"修改角色名称"},{"id":242,"shiroConf":"stuff:role:delete","name":"删除角色"},{"id":243,"shiroConf":"stuff:role:permissions","name":"设置权限"},{"id":244,"shiroConf":"stuff:manage:bind","name":"绑定小程序"},{"id":31,"shiroConf":"customer","name":"客户管理"},{"id":32,"shiroConf":"customer:view","name":"查看及搜索"},{"id":33,"shiroConf":"customer:create","name":"新建客户"},{"id":34,"shiroConf":"customer:move","name":"转移客户"},{"id":35,"shiroConf":"customer:delete","name":"删除客户"},{"id":36,"shiroConf":"customer:update","name":"编辑客户信息"},{"id":91,"shiroConf":"order","name":"订单管理"},{"id":92,"shiroConf":"order:view","name":"查看及搜索"},{"id":93,"shiroConf":"order:create","name":"新建订单"},{"id":94,"shiroConf":"order:again","name":"再发一单"},{"id":95,"shiroConf":"order:ticket","name":"下载委托单"},{"id":96,"shiroConf":"order:paid","name":"到款确认"},{"id":97,"shiroConf":"order:delete","name":"删除"},{"id":98,"shiroConf":"order:bindCustomer","name":"绑定客户"},{"id":99,"shiroConf":"order:update","name":"编辑订单"}]
reactDOM.render(<Tree config={ config } treeData={ treeData } />, document.getElementById('react-tree'))